language: node_js
node_js:
  - "8"
services:
  - postgresql
before_script:
  - yarn db:create && yarn db:migrate
install:
  - yarn
env:
  - JWT_SECRET=ASDasj212nsdaj!@Dadj121daja!@DADad
  - DB_PASS=
  - DB_USER=postgres
