language: node_js
node_js:
  - '10.6.0'
services:
  - postgresql
before_script:
  - yarn db:create && yarn db:migrate
  - yarn build
script:
  - yarn test:front:cov --updateSnapshot
  - bash <(curl -s https://codecov.io/bash) -t 04af45d6-4d36-4d3b-afe2-c2864484c1f3
  - yarn test:back:cov --forceExit
  - bash <(curl -s https://codecov.io/bash) -t 04af45d6-4d36-4d3b-afe2-c2864484c1f3
install:
  - yarn
env:
  - JWT_SECRET=ASDasj212nsdaj!@Dadj121daja!@DADad DB_PASS= DB_USER=postgres NODE_ENV=test
